apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-redis
  labels:
    app: dashboard-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-redis
  template:
    metadata:
      labels:
        app: dashboard-redis
    spec:
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: dashboard-redis-pvc
      containers:
        - name: redis
          # L8: Pin to a specific digest for supply-chain safety
          # redis:alpine SHA as of July 2026
          image: redis:alpine@sha256:328fe6a5822256d10de89c8c1f669a3f2ed3e9ee2dbd1549d0890bf33c22eaf8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          command:
            - redis-server
          args:
            - --requirepass
            - "$(REDIS_PASSWORD)"
            - --save
            - "60"
            - "1"
            - --appendonly
            - "yes"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dashboard-redis-password
                  key: redis-password
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
