apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-dashboard

resources:
  - namespace.yaml
  - sa.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - secret.yaml
  - deploy-backend.yaml
  - svc-backend.yaml
  - deploy-frontend.yaml
  - svc-frontend.yaml
  - deploy-redis.yaml
  - svc-redis.yaml
