apiVersion: v1
kind: Service
metadata:
  name: dashboard-frontend
  labels:
    app: dashboard-frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 5173
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: dashboard-frontend
